### ISSUE TITLE
Add placeholders in leaderboard so user doesn't get confused

### ISSUE THREAD

**Issue by GorjanP** [dejanovv/Multitask#14]
E.g if we have only 3 high scores present, the leaderboard should look like:
1. Name1 Score1
2. Name2 Score2
3. Name3 score3
4. -------- x
6. -------- x
7. -------- x
8. -------- x
9. -------- x
10. -------- x

**Comment by dejanovv** [comment]
y tho

**Comment by GorjanP** [comment]
so it's obvious that there are 10 available places on the leaderboard, an empty screen is barren

**Comment by dejanovv** [comment]
How stupid do you think our users will be? :D

**Comment by GorjanP** [comment]
Very

**Comment by dejanovv** [comment]
good convo

**Comment by dejanovv** [comment]
also productive
